import type { FieldSpec } from "./LifeDrawerForm"

/**
 * Per-table field specs for Life drawers. Single source of truth so the
 * create-drawer on a list page and the edit-drawer on a detail page render the
 * same form. Columns match the actual `life.*` schema (verified against
 * information_schema). If a column isn't in the schema, it's not here.
 */

const DOMAIN_OPTIONS = [
  { value: "health", label: "Health" },
  { value: "wealth", label: "Wealth" },
  { value: "relationships", label: "Relationships" },
  { value: "growth", label: "Growth" },
  { value: "career", label: "Career" },
  { value: "mind", label: "Mind" },
  { value: "spiritual", label: "Spiritual" },
  { value: "other", label: "Other" },
]

const HORIZON_OPTIONS = [
  { value: "today", label: "Today" },
  { value: "1_week", label: "1 week" },
  { value: "1_month", label: "1 month" },
  { value: "1_year", label: "1 year" },
  { value: "3_years", label: "3 years" },
  { value: "10_years", label: "10 years" },
  { value: "lifetime", label: "Lifetime" },
]

const GOAL_STATUS = [
  { value: "active", label: "Active" },
  { value: "on_hold", label: "On hold" },
  { value: "complete", label: "Complete" },
  { value: "dropped", label: "Dropped" },
]

const ISSUE_STATUS = [
  { value: "open", label: "Open" },
  { value: "in_progress", label: "In progress" },
  { value: "resolved", label: "Resolved" },
  { value: "archived", label: "Archived" },
]

const SEVERITY = [
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
  { value: "critical", label: "Critical" },
]

const PRIORITY = [
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
]

export const SPECS: Record<string, FieldSpec[]> = {
  life_goals: [
    { name: "title", label: "Title", required: true },
    { name: "description", label: "Description", type: "textarea", rows: 3 },
    { name: "why", label: "Why", type: "textarea", rows: 2 },
    { name: "domain", label: "Domain", type: "select", options: DOMAIN_OPTIONS },
    { name: "horizon", label: "Horizon", type: "select", options: HORIZON_OPTIONS },
    { name: "status", label: "Status", type: "select", options: GOAL_STATUS },
    { name: "progress", label: "Progress (%)", type: "number", min: 0, max: 100 },
  ],
  life_issues: [
    { name: "title", label: "Title", required: true },
    { name: "description", label: "Description", type: "textarea", rows: 3 },
    { name: "domain", label: "Domain", type: "select", options: DOMAIN_OPTIONS },
    { name: "severity", label: "Severity", type: "select", options: SEVERITY },
    { name: "status", label: "Status", type: "select", options: ISSUE_STATUS },
    { name: "target_date", label: "Target date", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  people: [
    { name: "name", label: "Name", required: true },
    { name: "category", label: "Category", placeholder: "family, friend, colleague…" },
    { name: "phone", label: "Phone" },
    { name: "email", label: "Email" },
    { name: "birthday", label: "Birthday", type: "date" },
    { name: "location", label: "Location" },
    { name: "how_we_met", label: "How we met", type: "textarea", rows: 2 },
    { name: "frequency_target", label: "Contact frequency", placeholder: "weekly, monthly, quarterly" },
    { name: "last_contact", label: "Last contact", type: "date" },
    {
      name: "contact_health",
      label: "Contact health",
      type: "select",
      options: [
        { value: "excellent", label: "Excellent" },
        { value: "good", label: "Good" },
        { value: "fading", label: "Fading" },
        { value: "cold", label: "Cold" },
      ],
    },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
    { name: "active", label: "Active", type: "checkbox" },
  ],
  interaction_logs: [
    { name: "person_id", label: "Person ID", required: true },
    { name: "date", label: "Date", type: "date", required: true },
    { name: "mode", label: "Mode", placeholder: "call, meet, text, email" },
    { name: "summary", label: "Summary", type: "textarea", rows: 3 },
  ],
  personal_projects: [
    { name: "name", label: "Name", required: true },
    { name: "category", label: "Category" },
    { name: "description", label: "Description", type: "textarea", rows: 3 },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "planning", label: "Planning" },
        { value: "active", label: "Active" },
        { value: "on_hold", label: "On hold" },
        { value: "complete", label: "Complete" },
        { value: "dropped", label: "Dropped" },
      ],
    },
    { name: "progress", label: "Progress (%)", type: "number", min: 0, max: 100 },
    { name: "start_date", label: "Start date", type: "date" },
    { name: "target_date", label: "Target date", type: "date" },
    { name: "next_action", label: "Next action" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  project_milestones: [
    { name: "project_id", label: "Project ID", required: true },
    { name: "title", label: "Title", required: true },
    { name: "due_date", label: "Due date", type: "date" },
    { name: "done", label: "Done", type: "checkbox" },
  ],
  trips: [
    { name: "destination", label: "Destination", required: true },
    { name: "type", label: "Type", placeholder: "leisure, business, family" },
    { name: "departure_date", label: "Departure", type: "date" },
    { name: "return_date", label: "Return", type: "date" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "planned", label: "Planned" },
        { value: "booked", label: "Booked" },
        { value: "in_progress", label: "In progress" },
        { value: "complete", label: "Complete" },
        { value: "cancelled", label: "Cancelled" },
      ],
    },
    { name: "budget", label: "Budget", type: "number", step: "0.01" },
    { name: "spent", label: "Spent", type: "number", step: "0.01" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  vehicles: [
    { name: "make", label: "Make", required: true },
    { name: "model", label: "Model" },
    { name: "year", label: "Year", type: "number" },
    { name: "reg_number", label: "Registration number" },
    { name: "fuel_type", label: "Fuel type" },
    { name: "insurance_expiry", label: "Insurance expiry", type: "date" },
    { name: "puc_expiry", label: "PUC expiry", type: "date" },
    { name: "service_due", label: "Service due", type: "date" },
    { name: "loan_status", label: "Loan status" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  vehicle_service_logs: [
    { name: "vehicle_id", label: "Vehicle ID", required: true },
    { name: "date", label: "Date", type: "date", required: true },
    { name: "odometer", label: "Odometer (km)", type: "number" },
    { name: "service_type", label: "Service type" },
    { name: "cost", label: "Cost", type: "number", step: "0.01" },
    { name: "workshop", label: "Workshop" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  habits: [
    { name: "name", label: "Name", required: true },
    { name: "category", label: "Category" },
    {
      name: "frequency",
      label: "Frequency",
      type: "select",
      options: [
        { value: "daily", label: "Daily" },
        { value: "weekdays", label: "Weekdays" },
        { value: "weekly", label: "Weekly" },
        { value: "custom", label: "Custom" },
      ],
    },
    { name: "target_description", label: "Target", placeholder: "e.g. 30 min of reading" },
    { name: "why", label: "Why", type: "textarea", rows: 2 },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "active", label: "Active" },
        { value: "paused", label: "Paused" },
        { value: "archived", label: "Archived" },
      ],
    },
    { name: "sort_order", label: "Sort order", type: "number" },
  ],
  habit_logs: [
    { name: "habit_id", label: "Habit ID", required: true },
    { name: "date", label: "Date", type: "date", required: true },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "done", label: "Done" },
        { value: "partial", label: "Partial" },
        { value: "skipped", label: "Skipped" },
      ],
    },
    { name: "note", label: "Note" },
  ],
  bucket_list: [
    { name: "title", label: "Title", required: true },
    { name: "category", label: "Category" },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "dreaming", label: "Dreaming" },
        { value: "planning", label: "Planning" },
        { value: "in_progress", label: "In progress" },
        { value: "complete", label: "Complete" },
      ],
    },
    { name: "completed_at", label: "Completed on", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  books: [
    { name: "title", label: "Title", required: true },
    { name: "author", label: "Author" },
    { name: "category", label: "Category" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "wishlist", label: "Wishlist" },
        { value: "reading", label: "Reading" },
        { value: "finished", label: "Finished" },
        { value: "abandoned", label: "Abandoned" },
      ],
    },
    { name: "rating", label: "Rating (1-5)", type: "number", min: 1, max: 5 },
    { name: "started_at", label: "Started", type: "date" },
    { name: "finished_at", label: "Finished", type: "date" },
    { name: "key_takeaway", label: "Key takeaway", type: "textarea", rows: 2 },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  courses: [
    { name: "title", label: "Title", required: true },
    { name: "platform", label: "Platform" },
    { name: "category", label: "Category" },
    { name: "instructor", label: "Instructor" },
    { name: "url", label: "URL", type: "url" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "wishlist", label: "Wishlist" },
        { value: "in_progress", label: "In progress" },
        { value: "complete", label: "Complete" },
        { value: "dropped", label: "Dropped" },
      ],
    },
    { name: "progress_pct", label: "Progress (%)", type: "number", min: 0, max: 100 },
    { name: "certificate_url", label: "Certificate URL", type: "url" },
    { name: "started_at", label: "Started", type: "date" },
    { name: "finished_at", label: "Finished", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  skills: [
    { name: "name", label: "Name", required: true },
    { name: "category", label: "Category" },
    { name: "current_level", label: "Current level (1-10)", type: "number", min: 1, max: 10 },
    { name: "target_level", label: "Target level (1-10)", type: "number", min: 1, max: 10 },
    { name: "last_practiced", label: "Last practiced", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  captures: [
    { name: "content", label: "Content", type: "textarea", rows: 4, required: true },
    { name: "source", label: "Source" },
    { name: "category", label: "Category" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "inbox", label: "Inbox" },
        { value: "processed", label: "Processed" },
        { value: "archived", label: "Archived" },
      ],
    },
    { name: "action_item", label: "Action item" },
  ],
  queue_items: [
    { name: "title", label: "Title", required: true },
    { name: "creator", label: "Creator" },
    { name: "type", label: "Type", placeholder: "video, article, podcast" },
    { name: "url", label: "URL", type: "url" },
    { name: "category", label: "Category" },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "queued", label: "Queued" },
        { value: "in_progress", label: "In progress" },
        { value: "done", label: "Done" },
        { value: "skipped", label: "Skipped" },
      ],
    },
  ],
  investments: [
    { name: "name", label: "Name", required: true },
    { name: "type", label: "Type", placeholder: "stock, mf, etf, crypto" },
    { name: "platform", label: "Platform" },
    { name: "units", label: "Units", type: "number", step: "0.0001" },
    { name: "buy_price", label: "Buy price", type: "number", step: "0.01" },
    { name: "invested_amount", label: "Invested amount", type: "number", step: "0.01" },
    { name: "current_value", label: "Current value", type: "number", step: "0.01" },
    { name: "last_updated", label: "Last updated", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  insurance_policies: [
    { name: "type", label: "Type", placeholder: "health, life, term, auto" },
    { name: "provider", label: "Provider" },
    { name: "policy_number", label: "Policy number" },
    { name: "insured_amount", label: "Insured amount", type: "number", step: "0.01" },
    { name: "premium", label: "Premium", type: "number", step: "0.01" },
    { name: "premium_frequency", label: "Premium frequency", placeholder: "monthly, yearly" },
    { name: "next_due", label: "Next due", type: "date" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "active", label: "Active" },
        { value: "lapsed", label: "Lapsed" },
        { value: "expired", label: "Expired" },
      ],
    },
    { name: "document_url", label: "Document URL", type: "url" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  life_transactions: [
    { name: "date", label: "Date", type: "date", required: true },
    {
      name: "type",
      label: "Type",
      type: "select",
      options: [
        { value: "income", label: "Income" },
        { value: "expense", label: "Expense" },
        { value: "transfer", label: "Transfer" },
      ],
    },
    { name: "category", label: "Category" },
    { name: "sub_category", label: "Sub-category" },
    { name: "amount", label: "Amount", type: "number", step: "0.01", required: true },
    { name: "currency", label: "Currency", placeholder: "INR" },
    { name: "account", label: "Account" },
    { name: "narration", label: "Narration" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
    { name: "receipt_url", label: "Receipt URL", type: "url" },
    { name: "itr_relevant", label: "ITR relevant", type: "checkbox" },
  ],
  blocked_money: [
    { name: "scheme", label: "Scheme", required: true },
    { name: "type", label: "Type" },
    { name: "amount_invested", label: "Amount invested", type: "number", step: "0.01" },
    { name: "date_invested", label: "Date invested", type: "date" },
    { name: "lock_in_until", label: "Lock-in until", type: "date" },
    { name: "current_value", label: "Current value", type: "number", step: "0.01" },
    { name: "maturity_value", label: "Maturity value", type: "number", step: "0.01" },
    { name: "account", label: "Account" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  debtors: [
    { name: "name", label: "Name", required: true },
    { name: "amount", label: "Amount", type: "number", step: "0.01" },
    { name: "since", label: "Since", type: "date" },
    { name: "expected_return", label: "Expected return", type: "date" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "outstanding", label: "Outstanding" },
        { value: "returned", label: "Returned" },
        { value: "written_off", label: "Written off" },
      ],
    },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  creditors: [
    { name: "name", label: "Name", required: true },
    { name: "amount", label: "Amount", type: "number", step: "0.01" },
    { name: "since", label: "Since", type: "date" },
    { name: "due_date", label: "Due date", type: "date" },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  monthly_budgets: [
    { name: "month", label: "Month (YYYY-MM)", required: true, placeholder: "2026-04" },
    { name: "category", label: "Category", required: true },
    { name: "budget_amount", label: "Budget amount", type: "number", step: "0.01" },
  ],
  emis: [
    { name: "name", label: "Name", required: true },
    { name: "type", label: "Type" },
    { name: "monthly_amount", label: "Monthly amount", type: "number", step: "0.01" },
    { name: "total_amount", label: "Total amount", type: "number", step: "0.01" },
    { name: "start_date", label: "Start date", type: "date" },
    { name: "end_date", label: "End date", type: "date" },
    { name: "paid_count", label: "Paid count", type: "number" },
    { name: "account", label: "Account" },
    { name: "active", label: "Active", type: "checkbox" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  supplements: [
    { name: "name", label: "Name", required: true },
    { name: "dosage", label: "Dosage" },
    { name: "timing", label: "Timing" },
    { name: "purpose", label: "Purpose" },
    { name: "brand", label: "Brand" },
    { name: "stock_qty", label: "Stock qty", type: "number" },
    { name: "reorder_date", label: "Reorder date", type: "date" },
    { name: "monthly_cost", label: "Monthly cost", type: "number", step: "0.01" },
    { name: "active", label: "Active", type: "checkbox" },
  ],
  doctors: [
    { name: "name", label: "Name", required: true },
    { name: "speciality", label: "Speciality" },
    { name: "hospital", label: "Hospital" },
    { name: "phone", label: "Phone" },
    { name: "last_visit", label: "Last visit", type: "date" },
    { name: "next_appointment", label: "Next appointment", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  physical_assets: [
    { name: "name", label: "Name", required: true },
    { name: "category", label: "Category" },
    { name: "purchase_date", label: "Purchase date", type: "date" },
    { name: "purchase_price", label: "Purchase price", type: "number", step: "0.01" },
    { name: "current_value", label: "Current value", type: "number", step: "0.01" },
    { name: "condition", label: "Condition" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  life_documents: [
    { name: "name", label: "Name", required: true },
    { name: "type", label: "Type" },
    { name: "number", label: "Number" },
    { name: "issued_by", label: "Issued by" },
    { name: "issue_date", label: "Issue date", type: "date" },
    { name: "expiry_date", label: "Expiry date", type: "date" },
    { name: "status", label: "Status" },
    { name: "document_url", label: "Document URL", type: "url" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  thought_notes: [
    { name: "title", label: "Title" },
    { name: "content", label: "Content", type: "textarea", rows: 6, required: true },
  ],
  decision_logs: [
    { name: "decision", label: "Decision", required: true },
    { name: "domain", label: "Domain", type: "select", options: DOMAIN_OPTIONS },
    { name: "date", label: "Date", type: "date" },
    { name: "options_considered", label: "Options considered", type: "textarea", rows: 3 },
    { name: "choice_made", label: "Choice made", type: "textarea", rows: 2 },
    { name: "why", label: "Why", type: "textarea", rows: 2 },
    { name: "outcome", label: "Outcome", type: "textarea", rows: 2 },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  wins: [
    { name: "title", label: "Title", required: true },
    { name: "domain", label: "Domain", type: "select", options: DOMAIN_OPTIONS },
    { name: "date", label: "Date", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  letters_to_self: [
    { name: "subject", label: "Subject", required: true },
    { name: "written_on", label: "Written on", type: "date" },
    { name: "open_on", label: "Open on", type: "date" },
    { name: "content", label: "Content", type: "textarea", rows: 8 },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "sealed", label: "Sealed" },
        { value: "opened", label: "Opened" },
      ],
    },
  ],
  relationship_events: [
    { name: "title", label: "Title", required: true },
    { name: "date", label: "Date", type: "date" },
    { name: "category", label: "Category" },
    { name: "location", label: "Location" },
    { name: "notes", label: "Notes", type: "textarea", rows: 3 },
  ],
  professional_network: [
    { name: "name", label: "Name", required: true },
    { name: "title", label: "Title" },
    { name: "company", label: "Company" },
    { name: "how_we_know", label: "How we know" },
    { name: "last_touchpoint", label: "Last touchpoint", type: "date" },
    { name: "linkedin_url", label: "LinkedIn URL", type: "url" },
    { name: "email", label: "Email" },
    { name: "phone", label: "Phone" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  net_worth_snapshots: [
    { name: "month", label: "Month (YYYY-MM)", required: true, placeholder: "2026-04" },
    { name: "total_assets", label: "Total assets", type: "number", step: "0.01" },
    { name: "total_liabilities", label: "Total liabilities", type: "number", step: "0.01" },
    { name: "net_worth", label: "Net worth", type: "number", step: "0.01" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  routines: [
    { name: "name", label: "Name", required: true },
    { name: "time_of_day", label: "Time of day", placeholder: "morning, evening" },
    { name: "duration_mins", label: "Duration (mins)", type: "number" },
    { name: "active", label: "Active", type: "checkbox" },
    { name: "sort_order", label: "Sort order", type: "number" },
  ],

  // Quick-log tables
  workout_logs: [
    { name: "date", label: "Date", type: "date", required: true },
    { name: "type", label: "Type", placeholder: "strength, cardio, yoga" },
    { name: "duration_mins", label: "Duration (mins)", type: "number" },
    { name: "energy_level", label: "Energy level (1-10)", type: "number", min: 1, max: 10 },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  sleep_logs: [
    { name: "date", label: "Date", type: "date", required: true },
    { name: "bedtime", label: "Bedtime", type: "time" },
    { name: "wake_time", label: "Wake time", type: "time" },
    { name: "hours", label: "Hours", type: "number", step: "0.1" },
    { name: "quality", label: "Quality (1-10)", type: "number", min: 1, max: 10 },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  vital_logs: [
    { name: "date", label: "Date", type: "date", required: true },
    { name: "weight_kg", label: "Weight (kg)", type: "number", step: "0.1" },
    { name: "bp_systolic", label: "BP systolic", type: "number" },
    { name: "bp_diastolic", label: "BP diastolic", type: "number" },
    { name: "heart_rate", label: "Heart rate", type: "number" },
    { name: "blood_glucose", label: "Blood glucose", type: "number", step: "0.1" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  mood_logs: [
    { name: "date", label: "Date", type: "date", required: true },
    { name: "mood", label: "Mood (1-10)", type: "number", min: 1, max: 10 },
    { name: "energy", label: "Energy (1-10)", type: "number", min: 1, max: 10 },
    { name: "tag", label: "Tag" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  meditation_logs: [
    { name: "date", label: "Date", type: "date", required: true },
    { name: "duration_mins", label: "Duration (mins)", type: "number" },
    { name: "type", label: "Type", placeholder: "breathwork, vipassana, guided" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  gratitude_logs: [
    { name: "date", label: "Date", type: "date", required: true },
    { name: "item_1", label: "Grateful for #1" },
    { name: "item_2", label: "Grateful for #2" },
    { name: "item_3", label: "Grateful for #3" },
  ],
  apps: [
    { name: "name", label: "Name", required: true },
    { name: "url", label: "URL", type: "url", placeholder: "https://…" },
    { name: "category", label: "Category", type: "select", required: true, options: [
      { value: "productivity", label: "Productivity" },
      { value: "communication", label: "Communication" },
      { value: "development", label: "Development" },
      { value: "design", label: "Design" },
      { value: "finance", label: "Finance" },
      { value: "infrastructure", label: "Infrastructure" },
      { value: "entertainment", label: "Entertainment" },
      { value: "health", label: "Health" },
      { value: "ai", label: "AI" },
      { value: "marketing", label: "Marketing" },
      { value: "shopping", label: "Shopping" },
      { value: "travel", label: "Travel" },
      { value: "social", label: "Social" },
      { value: "learning", label: "Learning" },
      { value: "utilities", label: "Utilities" },
      { value: "other", label: "Other" },
    ] },
    { name: "purpose", label: "Purpose", placeholder: "One-line description of what it does for you" },
    { name: "usage_frequency", label: "Usage frequency", type: "select", options: [
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
      { value: "monthly", label: "Monthly" },
      { value: "rarely", label: "Rarely" },
      { value: "archived", label: "Archived" },
    ] },
    { name: "is_favorite", label: "Favorite (show on dashboard)", type: "checkbox" },
    { name: "is_paid", label: "Paid app", type: "checkbox" },
    { name: "logo_url", label: "Logo URL override", type: "url", placeholder: "Leave blank to auto-derive from URL" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  app_subscriptions: [
    { name: "app_id", label: "App ID", required: true, placeholder: "life.apps.id uuid" },
    { name: "plan_name", label: "Plan", placeholder: "Pro, Team, Family, Lifetime…" },
    { name: "billing_cycle", label: "Billing cycle", type: "select", options: [
      { value: "monthly", label: "Monthly" },
      { value: "quarterly", label: "Quarterly" },
      { value: "annual", label: "Annual" },
      { value: "lifetime", label: "Lifetime" },
      { value: "trial", label: "Trial" },
    ] },
    { name: "amount", label: "Amount", type: "number", step: "0.01" },
    { name: "currency", label: "Currency", placeholder: "INR" },
    { name: "next_renewal", label: "Next renewal", type: "date" },
    { name: "auto_renew", label: "Auto-renew", type: "checkbox" },
    { name: "payment_method", label: "Payment method", placeholder: "HDFC Visa, Mercury USD, UPI…" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "active", label: "Active" },
      { value: "trial", label: "Trial" },
      { value: "cancelled", label: "Cancelled" },
      { value: "lapsed", label: "Lapsed" },
    ] },
    { name: "started_on", label: "Started on", type: "date" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  app_credentials: [
    { name: "app_id", label: "App ID", required: true, placeholder: "life.apps.id uuid" },
    { name: "login_type", label: "Login type", type: "select", options: [
      { value: "email", label: "Email + password" },
      { value: "username", label: "Username + password" },
      { value: "sso_google", label: "Google SSO" },
      { value: "sso_github", label: "GitHub SSO" },
      { value: "sso_apple", label: "Apple SSO" },
      { value: "passkey", label: "Passkey" },
      { value: "phone", label: "Phone OTP" },
    ] },
    { name: "identifier", label: "Identifier", placeholder: "Email or username used" },
    { name: "password_manager", label: "Password lives in", placeholder: "1Password, Bitwarden, browser, memory" },
    { name: "password_last_rotated", label: "Last rotated", type: "date" },
    { name: "two_factor_method", label: "2FA method", type: "select", options: [
      { value: "totp", label: "TOTP (Authy/1Password)" },
      { value: "hardware_key", label: "Hardware key" },
      { value: "sms", label: "SMS" },
      { value: "email", label: "Email" },
      { value: "none", label: "None" },
    ] },
    { name: "recovery_email", label: "Recovery email" },
    { name: "recovery_phone", label: "Recovery phone" },
    { name: "notes", label: "Notes", type: "textarea", rows: 2 },
  ],
  journal_entries: [
    { name: "date", label: "Date", type: "date", required: true },
    { name: "brain_dump", label: "Brain dump", type: "textarea", rows: 5 },
    { name: "best_part", label: "Best part of today", type: "textarea", rows: 2 },
    { name: "change_one_thing", label: "One thing to change", type: "textarea", rows: 2 },
    { name: "grateful_for", label: "Grateful for", type: "textarea", rows: 2 },
    { name: "worried_about", label: "Worried about", type: "textarea", rows: 2 },
    { name: "one_learning", label: "One learning", type: "textarea", rows: 2 },
    { name: "mood", label: "Mood (1-10)", type: "number", min: 1, max: 10 },
    { name: "energy", label: "Energy (1-10)", type: "number", min: 1, max: 10 },
    { name: "day_rating", label: "Day rating (1-10)", type: "number", min: 1, max: 10 },
  ],
}
